### PR TITLE
Assorted fixes for pipes on Windows

### LINKED ISSUE #485: Second uv_pipe_accept() returns EBADF on Windows
Originally I filed this bug with the luvit team:

https://github.com/luvit/luv/issues/177

...but I have tracked the bug down to libuv. To reproduce this issue you can grab the luvi source code and build it (on Windows) as such:

```bash
git clone https://github.com/luvit/luvi.git
cd luvi
make tiny
make
```

That will produce a binary in ```build\Release\luvi.exe```. If you download this minimal code snippet you can reproduce the error:

https://gist.github.com/brimworks/c129c707044359d30ed7

To run that code, place it in ```bug\main.lua``` and run this command:

```build\Release\luvi.exe bug```

More details on the exact problem are here:

https://github.com/libuv/libuv/pull/400

Basically, I've narrowed it down to this change (just the change to ```src\win\pipe.c```):

https://github.com/libuv/libuv/commit/fb5df542ace7d6735a9e8e09d7d8bb6b8abdc459

### PR DESCRIPTION
**Pull request by saghul**
Fixes #485
Closes #486 

R=@piscisaureus

I'll add a couple of tests later today.

### CODE REVIEW

**Comment by saghul** [comment]
CI: https://jenkins-iojs.nodesource.com/view/libuv/job/libuv+any-pr+multi/136/

**Comment by saghul** [comment]
Yay, build is green :-) @piscisaureus can you PTAL?

**Comment by saghul** [comment]
@bnoordhuis maybe you can PTAL? @piscisaureus is AWOL.

File: src/win/pipe.c [hunk 1]
```diff
@@ -471,6 +472,8 @@ void uv_pipe_endgame(uv_loop_t* loop, uv_pipe_t* handle) {
 
 
 void uv_pipe_pending_instances(uv_pipe_t* handle, int count) {
+  if (handle->flags & UV_HANDLE_BOUND)
+    return;
```
Comment (bnoordhuis) [inline src/win/pipe.c]: You could consider changing the return type from void to int so you can return UV_EBUSY here.

It's not technically an API break (existing code will just keep on ignoring the return value) and neither is it an ABI break due to how name mangling works in C.

File: test/test-pipe-connect-multiple.c [hunk 2]
```diff
@@ -0,0 +1,102 @@
...
+  conn = &connections[connection_cb_called];
+  r = uv_pipe_init(server->loop, conn, 0);
+  ASSERT(r == 0);
+
+  r = uv_accept(server, (uv_stream_t*)conn);
+  ASSERT(r == 0);
+
+  if (++connection_cb_called == NUM_CLIENTS &&
+      connect_cb_called == NUM_CLIENTS)
+    uv_stop(server->loop);
```
Comment (bnoordhuis) [inline test/test-pipe-connect-multiple.c]: I'd wrap this in braces for readability.

File: test/test-pipe-connect-multiple.c [hunk 3]
```diff
@@ -0,0 +1,102 @@
...
+}
+
+
+static void connect_cb(uv_connect_t* connect_req, int status) {
+  ASSERT(status == 0);
+  if (++connect_cb_called == NUM_CLIENTS &&
+      connection_cb_called == NUM_CLIENTS)
+    uv_stop(connect_req->handle->loop);
```
Comment (bnoordhuis) [inline test/test-pipe-connect-multiple.c]: Same here.

**Comment by bnoordhuis** [comment]
LGTM with two take-it-or-leave-it suggestions.

File: src/win/pipe.c (hunk 1 above)
Comment (saghul) [inline src/win/pipe.c]: Ah, I see. I'd go for doing it if need be, I doubt this will be a problem for anyone at this point. FWIW I had to dig what thing actually meant...

**Comment by saghul** [comment]
Thanks for the review Ben!
