### PR TITLE
Check cwd length before spawning on win32

### LINKED ISSUE #4684: Win32: spawning process in a folder beyond the MAX_PATH length fails in CreateProcessW
If we spawn a process in a folder where we either use or inherit a cwd that is longer than MAX_PATH, then the CreateProcessW call fails with 'INVALID_DIRECTORY'.

This is documented in Microsoft QnA as a limitation of the CreateProcess API that (at least for now) does not look to be scheduled for fixing. And 'easy' workaround is to shorten the path if it is in the MAX_PATH realm.

### PR DESCRIPTION
**Pull request by xoriath**
The CreateProcess API on Windows is still not longPathAware, even if the process itself is. So, if the cwd used for CreateProcess is too long, then the call fails with a 'INVALID_DIRECTORY' error.

To deal with this, check the length of the cwd and shorten it if it is longer than MAX_PATH.

This fixes #4684

### CODE REVIEW

File: src/win/process.c [hunk 1]
```diff
@@ -970,6 +971,31 @@ int uv_spawn(uv_loop_t* loop,
...
+    short_cwd_len = GetShortPathNameW(long_cwd, NULL, 0);
+    if (short_cwd_len == 0) {
+      err = GetLastError();
+      goto done;
+    }
+
+    cwd = (WCHAR*) uv__malloc(short_cwd_len * sizeof(WCHAR));
+    if (cwd == NULL) {
+      err = ERROR_OUTOFMEMORY;
+      goto done;
```
Comment (juanarbol) [inline src/win/process.c:987]:
```suggestion
      err = UV_ENOMEM;
      goto uv_done;
```

Maybe?

File: src/win/process.c [hunk 2]
```diff
@@ -970,6 +971,31 @@ int uv_spawn(uv_loop_t* loop,
...
+  if (cwd_len >= MAX_PATH) {
+    WCHAR* long_cwd = cwd;
+    DWORD short_cwd_len, r;
+    short_cwd_len = GetShortPathNameW(long_cwd, NULL, 0);
+    if (short_cwd_len == 0) {
+      err = GetLastError();
+      goto done;
+    }
+
+    cwd = (WCHAR*) uv__malloc(short_cwd_len * sizeof(WCHAR));
```
Comment (saghul) [inline src/win/process.c:984]: can't we allI think you could avoid this by having a stack allocated array of MAX_PATH size.

Comment (bnoordhuis) [reply src/win/process.c:984]: The counterargument is that `wchar_t[MAX_PATH]` is kind of biggish for an on-stack buffer (64 kB) but we do that elsewhere so I suppose it's okay? It's definitely easier to reason about.

**Review by bnoordhuis — APPROVED** [review]
Not our resident win32 expert but LGTM insofar I can judge such things.

**Review by saghul — APPROVED** [review]
👍  I had missed that we already allocate cwd and you reused it, nice!
