### PR TITLE
win,pipe: ipc code does not support async read

### LINKED ISSUE #4548: win,pipe: regression after #4470
So after the new `v1.49.0` release, the Node.js test suite is failing pretty badly specially with the `child_process` tests. See:
https://github.com/nodejs/node/pull/55114. My bad I didn't catch this before the release, but was having problems with the CI on Windows.

I've been looking at the changes and it seems to come from the change in https://github.com/libuv/libuv/pull/4470.
So as an example, when running the following test, the process never exits:
```
 out/Release/node.exe test/parallel/test-child-process-fork.js
 ```
 
 Reverting all changes in `win/pipe.c` make the tests to pass again (at least most of them)
 
 /cc @vtjnash

### PR DESCRIPTION
**Pull request by vtjnash**
The implementation of IPC pipe in libuv on Windows does not properly support async reading. This means we cannot set the more parameter without likely causing hangs. Sorry this is yet another followup to #4511.

Fixes #4548

### CODE REVIEW

File: src/win/pipe.c [hunk 1]
```diff
@@ -2094,17 +2094,13 @@ static int uv__pipe_read_ipc(uv_loop_t* loop, uv_pipe_t* handle) {
...
-   * more data. */
-  if (more && *data_remaining == 0) {
-    /* TODO: use PeekNamedPipe to see if it is really worth trying to do
-     * another ReadFile call. */
-  }
-
+   * more data. Calling uv__pipe_read_exactly will hang if there isn't data
+   * available, so we cannot do this unless we are guaranteed not to reach that.
+   */
+  more = *data_remaining > 0;
```
Comment (saghul) [inline src/win/pipe.c:2103]: Looks like more is not really needed now?

I see we set it above but it's overwritten here.

Comment (vtjnash) [reply src/win/pipe.c:2103]: Not required, but I like to give my return values names, when possible

**Review by santigimeno — APPROVED** [review]
Tested on Node.js test suite and works. Still some failing tests but they all seem unrelated.
