### PR TITLE
Fix race condition in uv__init_console

### LINKED ISSUE #3970: Race condition in libuv console causes crash (assertion failure) on Windows
* **Version**: Node.js v18.3.0 to all current versions, which I think is libuv v1.44.2 and up
* **Platform**: Windows 10, Windows 11, Windows Server 2022

I originally reported this to Node.js.   Here's the original bug report: https://github.com/nodejs/node/issues/47715

I represent a team using Node.js within Microsoft.  When running Node on machines under heavy load, we have found that some Node processes fail, due to an assertion failing within `/deps/uv/win/tty.c`.  This is the assertion that is failing (edited for brevity):

```c++
static void uv__tty_console_signal_resize(void) {
...
  uv_mutex_lock(&uv__tty_console_resize_mutex);
  assert(uv__tty_console_width != -1 && uv__tty_console_height != -1);      <-- this fails
  if (width != uv__tty_console_width || height != uv__tty_console_height) {
...
  }
}
```

I believe the root cause is that there is a race condition in `uv_console_init()`:

```c++
void uv_console_init(void) {
  if (uv_sem_init(&uv_tty_output_lock, 1))
    abort();
  uv__tty_console_handle = CreateFileW(L"CONOUT$",
                                       GENERIC_READ | GENERIC_WRITE,
                                       FILE_SHARE_WRITE,
                                       0,
                                       OPEN_EXISTING,
                                       0,
                                       0);
  if (uv__tty_console_handle != INVALID_HANDLE_VALUE) {
    CONSOLE_SCREEN_BUFFER_INFO sb_info;
    QueueUserWorkItem(uv__tty_console_resize_message_loop_thread,       <-- this starts a task in a thread pool
                      NULL,
                      WT_EXECUTELONGFUNCTION);
    uv_mutex_init(&uv__tty_console_resize_mutex);
    if (GetConsoleScreenBufferInfo(uv__tty_console_handle, &sb_info)) {
      uv__tty_console_width = sb_info.dwSize.X;
      uv__tty_console_height = sb_info.srWindow.Bottom - sb_info.srWindow.Top + 1;
    }
  }
}
```

This code starts a task in a thread pool, and then queries the console size.  If the thread pool task wakes up fast enough, then it will run the code that queries the console buffer size and attempts to resize it, before the first query of that console buffer succeeds, leading to the assertion failure.

Also, the worker thread can call `uv_mutex_lock(&uv__tty_console_resize_mutex);` before the mutex is even initialized, which would be another source of crashes.

We see this on build machines, where we spawn 140,000+ Node.js processes on machines with very large CPU counts (128 or more cores).  It is more common when running VMs than when running on bare metal (where we have rarely seen this).

We are running Node.js v18.13.0.  I have checked the sources, and this issue appears to be present in v18.13.0 and all later versions, up to and including main.

The fix should be to move the `QueueUserWorkItem` call after the `if (GetConsoleScreenBuffer(...)) { ... }` block.  That should guarantee that the mutex is properly initialized, and that the first call to `GetConsoleScreenBuffer` has occurred, before the resizing thread can win the race.

# Reproducing

It is not easy to reproduce this bug.  We see this when running Windows builds (as in, building Windows itself), where we run more than 140,000 Node.js processes.  Even then, the frequency of this bug is 1 or 2 instances per build. That's the frequency when running on builds within VMs; when running in a host OS (no VM), the repro rate is lower (only a few observed cases).

### PR DESCRIPTION
**Pull request by sivadeilra**
This fixes #3970. It moves the initialization of two things to the point before where a thread task is spawned.

The existing code has a race condition. Calling `QueueUserWorkItem` queues a work item on a thread pool.  It's possible for that work item to begin executing even before the `QueueUserWorkItem` function returns.

On heavily-loaded systems, especially VMs where scheduling can be unpredictable due to hypervisor interrupts, it is possible for the worker function that is queued by `QueueUserWorkItem` to query the console size and attempt to acquire `uv__tty_console_resize_mutex` before it is initialized.  That's undefined behavior, and in practice, it can cause a crash.  Separately, the worker code also asserts that the `uv_tty_console_width` (and height) variables have been initialized, but they are not guaranteed to be.

The fix is simple.  Only queue the worker task after initializing the mutex and querying the initial values of the console buffer size.

I represent a team at Microsoft that is using Node.js heavily.  We found that this bug really does trigger on heavily-loaded build machines.  The repro takes hours and requires a lot of machine setup, so it's not an easy repro.  I was able to reproduce it much more easily by adding `Sleep(1000);` immediately after the call to `QueueUserWorkItem`, and repeatedly spawning Node with a test binary that printed messages to the console.  With this change, the crash no longer reproduces.

### CODE REVIEW

File: src/win/tty.c [hunk 1]
```diff
@@ -170,14 +170,14 @@ void uv__console_init(void) {
...
-                      NULL,
-                      WT_EXECUTELONGFUNCTION);
     uv_mutex_init(&uv__tty_console_resize_mutex);
     if (GetConsoleScreenBufferInfo(uv__tty_console_handle, &sb_info)) {
       uv__tty_console_width = sb_info.dwSize.X;
       uv__tty_console_height = sb_info.srWindow.Bottom - sb_info.srWindow.Top + 1;
     }
+    QueueUserWorkItem(uv__tty_console_resize_message_loop_thread,
+                      NULL,
+                      WT_EXECUTELONGFUNCTION);
```
Comment (bnoordhuis) [inline src/win/tty.c:180]: Not a Windows programmer, maybe the synchronization guarantees for QueueUserWorkItem() are such that it isn't necessary, but adding a critical section looks more Obviously Correct.
```suggestion
    uv_mutex_init(&uv__tty_console_resize_mutex);
    if (GetConsoleScreenBufferInfo(uv__tty_console_handle, &sb_info)) {
      uv_mutex_lock(&uv__tty_console_resize_mutex);
      uv__tty_console_width = sb_info.dwSize.X;
      uv__tty_console_height = sb_info.srWindow.Bottom - sb_info.srWindow.Top + 1;
      uv_mutex_unlock(&uv__tty_console_resize_mutex);
    }
    QueueUserWorkItem(uv__tty_console_resize_message_loop_thread,
                      NULL,
                      WT_EXECUTELONGFUNCTION);
```
There's an assert around line 2426 that looks like it can (still?) be hit now:
```c
assert(uv__tty_console_width != -1 && uv__tty_console_height != -1);
```
I'd simply remove it.

Comment (sivadeilra) [reply src/win/tty.c:180]: Sure, that's valid.  I was aiming for the least-disruptive change.

Comment (sivadeilra) [reply src/win/tty.c:180]: I removed the assert (agreed it's unnecessary), but left the initialization order as it is.  It doesn't make sense to acquire a mutex in the same function that initializes the mutex.

**Review by vtjnash — APPROVED** [review]

File: src/win/tty.c (hunk 1 above)
Comment (bnoordhuis) [reply src/win/tty.c:180]: > It doesn't make sense to acquire a mutex in the same function that initializes the mutex.

That's not the point I'm making. Wrapping the assignments in a critical section ensures other threads see the assignments, and in the right order.

QueueUserWorkItem() probably issues some kind of memory barrier but why take chances? This isn't performance-critical code.

**Review by StefanStojanovic — APPROVED** [review]

File: src/win/tty.c (hunk 1 above)
Comment (sivadeilra) [reply src/win/tty.c:180]: Ahh, I see what you mean.  On Windows, there is definitely an implied memory fence between all operations that start threads (or their equivalents, like QueueUserWorkItem), and the body of the thread.  Without that implied barrier, you would need to manually insert barriers any time you created a context object that is passed to CreateThread, QueueUserWorkItem, etc.

**Comment by sivadeilra** [comment]
Is there anything else that needs to be done before this is merged?  Or does this team wait and merge things as a batch?

**Review by bnoordhuis — APPROVED** [review]
LGTM. I'll merge it.
