### PR TITLE
test: fix ipc_send_recv_pipe flakiness

### LINKED ISSUE #3469: Intermittent issue seen on SPARC platform with test ipc_send_recv_pipe
* **Version**: 1.42.0
* **Platform**: SunOS 5.11 11.4.42.109.0 sun4v sparc non-virtualized

While testing libuv on SPARC (SPARC-T4-2) running Solaris 11.4
test `ipc_send_recv_pipe` is seen to intermittently fail.
Versions tested include v1.41.0, v1.41.1 and v1.42.0.

The stack trace on failure is:

    (dbx) where
    current thread: t@1
      [1] __lwp_sigqueue(0x0, 0xa00bcbd6fb0, 0x6, 0x0, 0xffffffffffffffff, 0x0), at 0x7fffff0e26b0
      [2] raise(0x6, 0xffffffff7fff8750, 0x5, 0x5, 0x0, 0x0), at 0x7fffff02ba64
      [3] abort(0x1, 0x1210, 0x0, 0x1000, 0x7fffff224000, 0x9b), at 0x7ffffeffaa24
    =>[4] read_cb(handle = 0x1003624f0, nread = <value unavailable>, rdbuf = <value unavailable>) (optimized), at 0x1000bbd20 (line ~323) in "test-ipc-send-recv.c"
      [5] uv__read(stream = 0x1003624f0) (optimized), at 0x7ffff1533d6c (line ~1192) in "stream.c"
      [6] uv__stream_io(loop = <value unavailable>, w = 0x100362578, events = 8U) (optimized), at 0x7ffff153410c (line ~1316) in "stream.c"
      [7] uv__io_poll(loop = 0x7ffff1700140, timeout = -1) (optimized), at 0x7ffff153be9c (line ~311) in "sunos.c"
      [8] uv_run(loop = 0x7ffff1700140, mode = UV_RUN_DEFAULT) (optimized), at 0x7ffff151f1c0 (line ~389) in "core.c"
      [9] run_ipc_send_recv_helper(loop = <value unavailable>, inprocess = <value unavailable>) (inlined), line 398 in "test-ipc-send-recv.c"
      [10] ipc_send_recv_helper() (optimized), line 410 in "test-ipc-send-recv.c"
    (dbx)

Note that:

-   attempts to truss(1) the test cause it to pass.
-   intermittent is between 30-50% of the time when running the test
    in a loop on a system that is quiescent.

Looking into a possible cause I believe the issue is with the test itself.

As the stack shows, `uv_read` called the test's call-back function;
the specific line is `src/unix/stream.c'uv__read:1192`, shown here with some context:

        1162          if (!is_ipc) {
        1163        do {
        1164          nread = read(uv__stream_fd(stream), buf.base, buf.len);
        1165        }
        1166        while (nread < 0 && errno == EINTR);
        1167      } else {
        1168        /* ipc uses recvmsg */
        1169        msg.msg_flags = 0;
        1170        msg.msg_iov = (struct iovec*) &buf;
        1171        msg.msg_iovlen = 1;
        1172        msg.msg_name = NULL;
        1173        msg.msg_namelen = 0;
        1174        /* Set up to receive a descriptor even if one isn't in the message */
        1175        msg.msg_controllen = sizeof(cmsg_space);
        1176        msg.msg_control = cmsg_space;
        1177  
        1178        do {
        1179          nread = uv__recvmsg(uv__stream_fd(stream), &msg, 0);
        1180        }
        1181        while (nread < 0 && errno == EINTR);
        1182      }
        1183  
        1184      if (nread < 0) {
        1185        /* Error */
        1186        if (errno == EAGAIN || errno == EWOULDBLOCK) {  /* SJM Yes, errno 11 : EAGAIN */
        1187          /* Wait for the next one. */  /* SJM does it really wait? */
        1188          if (stream->flags & UV_HANDLE_READING) {  /* SJM, yes this flag is set */
        1189            uv__io_start(stream->loop, &stream->io_watcher, POLLIN);  /* SJM Does not appear to wait */
        1190            uv__stream_osx_interrupt_select(stream); /* SJM NOP */
        1191          }
        1192          stream->read_cb(stream, 0, &buf);    /* <---- SJM */

Thus we can deduce that `uv__recmsg()` / `recvmsg()` returned a negative
result and the errno was 11, EAGAIN (which on Solaris is the same as
EWOULDBLOCK).  The call to `stream->read_cb (uv_read_cb)` as shown
explicitly passes in `nread` as 0.

Documentation ([`uv_stream_t` — Stream handle — libuv documentation](http://docs.libuv.org/en/v1.x/stream.html)) states

    This is equivalent to EAGAIN or EWOULDBLOCK under read(2).

The call-back routine does not check for `nread == 0`, and so erroneously 
continues until an assertion is hit.

Modifying the test to simply return when `nread == 0` prevents assertions,
and the test passes.  Though I have not confirmed that it the right
solution and seek advice or confirmation.

Thanks.

### PR DESCRIPTION
**Pull request by bnoordhuis**
The read callback failed to handle the `nread == 0` case, which is rare
to non-existent on the systems we test on but apparently happens often
enough on Solaris on SPARC to draw attention.

Fixes #3469.

### CODE REVIEW

**Review by cjihrig — APPROVED** [review]

File: test/test-ipc-send-recv.c [hunk 1]
```diff
@@ -309,7 +309,9 @@ static void read_cb(uv_stream_t* handle,
   }
 
   pipe = (uv_pipe_t*) handle;
-  do {
+  ASSERT_EQ(pipe, &ctx2.channel);
+
```
Comment (vtjnash) [inline test/test-ipc-send-recv.c:313]:
```suggestion
    ASSERT_GE(nread, 0);

```
